do $$
begin
  create type public.project_type as enum ('book', 'free');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.project_status as enum ('planned', 'current', 'done');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.study_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  type public.project_type not null default 'book',
  status public.project_status not null default 'planned',
  total_pages integer not null default 1 check (total_pages > 0),
  image_url text not null default '',
  goal text not null default '',
  starts_on date not null default current_date,
  ends_on date,
  created_by uuid references public.study_members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists study_projects_one_current
  on public.study_projects ((status))
  where status = 'current';

alter table public.study_sessions
  add column if not exists project_id bigint references public.study_projects(id) on delete set null;

alter table public.study_sessions
  add column if not exists project_progress integer not null default 0 check (project_progress >= 0);

insert into public.study_projects (
  title,
  type,
  status,
  total_pages,
  image_url,
  goal,
  starts_on,
  created_by
)
select
  '프론트엔드 운영 도구 학습',
  'book',
  'current',
  greatest(coalesce(sum(progress_target), 1), 1)::integer,
  '',
  '회차별 학습 내용을 하나의 프로젝트 진도로 관리한다.',
  coalesce(min(starts_on), current_date),
  (select id from public.study_members where role in ('owner', 'admin') order by created_at limit 1)
from public.study_sessions
where not exists (select 1 from public.study_projects);

update public.study_sessions
set project_id = (select id from public.study_projects order by id limit 1),
    project_progress = progress_current
where project_id is null;

create index if not exists study_projects_created_by_idx on public.study_projects(created_by);
create index if not exists study_sessions_project_id_idx on public.study_sessions(project_id);

alter table public.study_projects enable row level security;

drop policy if exists "study projects select active" on public.study_projects;
create policy "study projects select active"
  on public.study_projects for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

drop policy if exists "study projects insert managers" on public.study_projects;
create policy "study projects insert managers"
  on public.study_projects for insert
  to authenticated
  with check (app_private.can_manage_study() or app_private.is_bootstrap_open());

drop policy if exists "study projects update managers" on public.study_projects;
create policy "study projects update managers"
  on public.study_projects for update
  to authenticated
  using (app_private.can_manage_study())
  with check (app_private.can_manage_study());

drop policy if exists "study projects delete managers" on public.study_projects;
create policy "study projects delete managers"
  on public.study_projects for delete
  to authenticated
  using (app_private.can_manage_study());

drop trigger if exists study_projects_set_updated_at on public.study_projects;
create trigger study_projects_set_updated_at
  before update on public.study_projects
  for each row execute function public.set_updated_at();

drop trigger if exists projects_activity on public.study_projects;
create trigger projects_activity
  after insert or update or delete on public.study_projects
  for each row execute function app_private.add_activity_event();
