create extension if not exists pgcrypto with schema extensions;
create schema if not exists app_private;

do $$
begin
  create type public.study_member_role as enum ('owner', 'admin', 'facilitator', 'member');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.session_status as enum ('planned', 'upcoming', 'current', 'done');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.document_kind as enum ('material', 'presentation');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.progress_status as enum ('planned', 'active', 'done');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.penalty_status as enum ('open', 'settled');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '새 사용자',
  github_username text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.study_members (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique references public.profiles(id) on delete set null,
  member_uid text not null unique,
  display_name text not null,
  invite_email text unique,
  github_username text unique,
  role public.study_member_role not null default 'member',
  role_label text not null default '스터디원',
  color text not null default '#0f766e',
  active boolean not null default true,
  material_root text not null,
  presentation_root text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint study_members_member_uid_format check (member_uid ~ '^[a-z0-9][a-z0-9_-]*$'),
  constraint study_members_color_format check (color ~ '^#[0-9a-fA-F]{6}$')
);

create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  title text not null,
  week integer not null unique check (week > 0),
  status public.session_status not null default 'planned',
  starts_on date not null,
  ends_on date not null,
  presentation_on date not null,
  start_time time not null default '20:00',
  end_time time not null default '21:30',
  location text not null default 'Discord',
  goal text not null default '',
  facilitator_member_id uuid references public.study_members(id) on delete set null,
  presenter_member_ids uuid[] not null default '{}',
  agenda text[] not null default '{}',
  resources text[] not null default '{}',
  progress_label text not null default '진도',
  progress_current integer not null default 0 check (progress_current >= 0),
  progress_target integer not null default 1 check (progress_target > 0),
  progress_unit text not null default '개',
  created_by uuid references public.study_members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint study_sessions_date_range check (starts_on <= ends_on and presentation_on between starts_on and ends_on),
  constraint study_sessions_progress_range check (progress_current <= progress_target)
);

create unique index if not exists study_sessions_one_current
  on public.study_sessions ((status))
  where status = 'current';

create table if not exists public.document_folders (
  id uuid primary key default gen_random_uuid(),
  kind public.document_kind not null,
  path text not null,
  name text not null,
  parent_path text,
  owner_member_id uuid references public.study_members(id) on delete cascade,
  session_id bigint references public.study_sessions(id) on delete cascade,
  created_by uuid references public.study_members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_folders_path_format check (path !~ '(^/|//|/$)'),
  constraint document_folders_presentation_session check (kind = 'material' or session_id is not null),
  unique (kind, path)
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  kind public.document_kind not null,
  path text not null unique,
  title text not null,
  summary text not null default '',
  owner_member_id uuid references public.study_members(id) on delete set null,
  session_id bigint references public.study_sessions(id) on delete set null,
  tags text[] not null default '{}',
  body text not null default '',
  created_by uuid references public.study_members(id) on delete set null,
  updated_by uuid references public.study_members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint documents_path_format check (path ~ '\.md$' and path !~ '(^/|//)'),
  constraint documents_presentation_session check (kind = 'material' or session_id is not null)
);

create index if not exists documents_kind_path_idx on public.documents(kind, path);
create index if not exists documents_owner_idx on public.documents(owner_member_id);
create index if not exists documents_session_idx on public.documents(session_id);

create table if not exists public.document_versions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.documents(id) on delete cascade,
  version_number integer not null,
  title text not null,
  summary text not null default '',
  path text not null,
  tags text[] not null default '{}',
  body text not null,
  edited_by uuid references public.study_members(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (document_id, version_number)
);

create table if not exists public.progress_topics (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  owner_member_id uuid references public.study_members(id) on delete set null,
  current integer not null default 0 check (current >= 0),
  target integer not null check (target > 0),
  unit text not null default '개',
  status public.progress_status not null default 'planned',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint progress_topics_range check (current <= target)
);

create table if not exists public.penalties (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  member_id uuid not null references public.study_members(id) on delete cascade,
  session_id bigint references public.study_sessions(id) on delete set null,
  type text not null,
  reason text not null,
  amount integer not null check (amount >= 0),
  status public.penalty_status not null default 'open',
  due_date date not null,
  settled_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint penalties_settled_at check ((status = 'settled' and settled_at is not null) or (status = 'open' and settled_at is null))
);

create table if not exists public.activity_events (
  id uuid primary key default gen_random_uuid(),
  actor_member_id uuid references public.study_members(id) on delete set null,
  event_type text not null,
  entity_table text not null,
  entity_id text,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.documents(id) on delete cascade,
  bucket_id text not null default 'study-attachments',
  object_path text not null unique,
  file_name text not null,
  content_type text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  uploaded_by uuid references public.study_members(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function app_private.current_member_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.study_members
  where profile_id = auth.uid()
    and active = true
  limit 1
$$;

create or replace function app_private.current_member_role()
returns public.study_member_role
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.study_members
  where profile_id = auth.uid()
    and active = true
  limit 1
$$;

create or replace function app_private.is_active_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select app_private.current_member_id() is not null
$$;

create or replace function app_private.can_manage_study()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(app_private.current_member_role() in ('owner', 'admin', 'facilitator'), false)
$$;

create or replace function app_private.is_bootstrap_open()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select not exists (
    select 1
    from public.study_members
    where active = true
      and profile_id is not null
      and role in ('owner', 'admin')
  )
$$;

create or replace function app_private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  preferred_name text;
  preferred_github text;
begin
  preferred_name := coalesce(
    new.raw_user_meta_data ->> 'name',
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'user_name',
    split_part(coalesce(new.email, '새 사용자'), '@', 1)
  );
  preferred_github := coalesce(
    new.raw_user_meta_data ->> 'user_name',
    new.raw_user_meta_data ->> 'preferred_username'
  );

  insert into public.profiles (id, email, display_name, github_username, avatar_url)
  values (
    new.id,
    new.email,
    preferred_name,
    preferred_github,
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = excluded.display_name,
      github_username = excluded.github_username,
      avatar_url = excluded.avatar_url,
      updated_at = now();

  update public.study_members
  set profile_id = new.id,
      updated_at = now()
  where profile_id is null
    and invite_email is not null
    and lower(invite_email) = lower(coalesce(new.email, ''));

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute function app_private.handle_new_auth_user();

create or replace function app_private.create_document_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_version integer;
begin
  select coalesce(max(version_number), 0) + 1
  into next_version
  from public.document_versions
  where document_id = new.id;

  insert into public.document_versions (
    document_id,
    version_number,
    title,
    summary,
    path,
    tags,
    body,
    edited_by
  )
  values (
    new.id,
    next_version,
    new.title,
    new.summary,
    new.path,
    new.tags,
    new.body,
    coalesce(new.updated_by, new.created_by)
  );

  return new;
end;
$$;

drop trigger if exists documents_version_insert on public.documents;
create trigger documents_version_insert
  after insert on public.documents
  for each row execute function app_private.create_document_version();

drop trigger if exists documents_version_update on public.documents;
create trigger documents_version_update
  after update of title, summary, path, tags, body on public.documents
  for each row
  when (
    old.title is distinct from new.title
    or old.summary is distinct from new.summary
    or old.path is distinct from new.path
    or old.tags is distinct from new.tags
    or old.body is distinct from new.body
  )
  execute function app_private.create_document_version();

create or replace function app_private.add_activity_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid;
  summary_text text;
begin
  actor := app_private.current_member_id();

  if tg_table_name = 'documents' then
    summary_text := case tg_op
      when 'INSERT' then '문서 생성: ' || new.title
      when 'UPDATE' then '문서 수정: ' || new.title
      when 'DELETE' then '문서 삭제: ' || old.title
    end;
  elsif tg_table_name = 'study_sessions' then
    summary_text := case tg_op
      when 'INSERT' then '회차 생성: ' || new.title
      when 'UPDATE' then '회차 수정: ' || new.title
      when 'DELETE' then '회차 삭제: ' || old.title
    end;
  else
    summary_text := tg_table_name || ' ' || tg_op;
  end if;

  insert into public.activity_events (actor_member_id, event_type, entity_table, entity_id, summary)
  values (
    actor,
    lower(tg_op),
    tg_table_name,
    case when tg_op = 'DELETE' then old.id::text else new.id::text end,
    summary_text
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists documents_activity on public.documents;
create trigger documents_activity
  after insert or update or delete on public.documents
  for each row execute function app_private.add_activity_event();

drop trigger if exists sessions_activity on public.study_sessions;
create trigger sessions_activity
  after insert or update or delete on public.study_sessions
  for each row execute function app_private.add_activity_event();

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles',
    'study_members',
    'study_sessions',
    'document_folders',
    'documents',
    'progress_topics',
    'penalties'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', table_name, table_name);
    execute format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end $$;

alter table public.profiles enable row level security;
alter table public.study_members enable row level security;
alter table public.study_sessions enable row level security;
alter table public.document_folders enable row level security;
alter table public.documents enable row level security;
alter table public.document_versions enable row level security;
alter table public.progress_topics enable row level security;
alter table public.penalties enable row level security;
alter table public.activity_events enable row level security;
alter table public.attachments enable row level security;

create policy "profiles select active members or self"
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "profiles insert self"
  on public.profiles for insert
  to authenticated
  with check (id = auth.uid());

create policy "profiles update self"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "study members select active or bootstrap"
  on public.study_members for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "study members insert managers or bootstrap"
  on public.study_members for insert
  to authenticated
  with check (
    app_private.can_manage_study()
    or (
      app_private.is_bootstrap_open()
      and profile_id = auth.uid()
      and role in ('owner', 'admin')
    )
  );

create policy "study members update managers or self"
  on public.study_members for update
  to authenticated
  using (
    app_private.can_manage_study()
    or profile_id = auth.uid()
    or app_private.is_bootstrap_open()
  )
  with check (
    app_private.can_manage_study()
    or profile_id = auth.uid()
    or app_private.is_bootstrap_open()
  );

create policy "study members delete managers"
  on public.study_members for delete
  to authenticated
  using (app_private.can_manage_study());

create policy "study sessions select active"
  on public.study_sessions for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "study sessions insert managers"
  on public.study_sessions for insert
  to authenticated
  with check (app_private.can_manage_study() or app_private.is_bootstrap_open());

create policy "study sessions update managers"
  on public.study_sessions for update
  to authenticated
  using (app_private.can_manage_study())
  with check (app_private.can_manage_study());

create policy "study sessions delete managers"
  on public.study_sessions for delete
  to authenticated
  using (app_private.can_manage_study());

create policy "folders select active"
  on public.document_folders for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "folders insert active"
  on public.document_folders for insert
  to authenticated
  with check (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "folders update owner or manager"
  on public.document_folders for update
  to authenticated
  using (app_private.can_manage_study() or created_by = app_private.current_member_id())
  with check (app_private.can_manage_study() or created_by = app_private.current_member_id());

create policy "folders delete owner or manager"
  on public.document_folders for delete
  to authenticated
  using (app_private.can_manage_study() or created_by = app_private.current_member_id());

create policy "documents select active"
  on public.documents for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "documents insert active"
  on public.documents for insert
  to authenticated
  with check (
    app_private.is_active_member()
    and coalesce(created_by, app_private.current_member_id()) = app_private.current_member_id()
  );

create policy "documents update owner or manager"
  on public.documents for update
  to authenticated
  using (app_private.can_manage_study() or owner_member_id = app_private.current_member_id() or created_by = app_private.current_member_id())
  with check (app_private.can_manage_study() or owner_member_id = app_private.current_member_id() or created_by = app_private.current_member_id());

create policy "documents delete owner or manager"
  on public.documents for delete
  to authenticated
  using (app_private.can_manage_study() or owner_member_id = app_private.current_member_id() or created_by = app_private.current_member_id());

create policy "versions select active"
  on public.document_versions for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "versions insert active"
  on public.document_versions for insert
  to authenticated
  with check (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "progress select active"
  on public.progress_topics for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "progress insert managers"
  on public.progress_topics for insert
  to authenticated
  with check (app_private.can_manage_study());

create policy "progress update owner or manager"
  on public.progress_topics for update
  to authenticated
  using (app_private.can_manage_study() or owner_member_id = app_private.current_member_id())
  with check (app_private.can_manage_study() or owner_member_id = app_private.current_member_id());

create policy "progress delete managers"
  on public.progress_topics for delete
  to authenticated
  using (app_private.can_manage_study());

create policy "penalties select active"
  on public.penalties for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "penalties insert managers"
  on public.penalties for insert
  to authenticated
  with check (app_private.can_manage_study());

create policy "penalties update managers"
  on public.penalties for update
  to authenticated
  using (app_private.can_manage_study())
  with check (app_private.can_manage_study());

create policy "penalties delete managers"
  on public.penalties for delete
  to authenticated
  using (app_private.can_manage_study());

create policy "activity select active"
  on public.activity_events for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "activity insert active"
  on public.activity_events for insert
  to authenticated
  with check (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "attachments select active"
  on public.attachments for select
  to authenticated
  using (app_private.is_active_member() or app_private.is_bootstrap_open());

create policy "attachments insert document editors"
  on public.attachments for insert
  to authenticated
  with check (
    app_private.is_active_member()
    and exists (
      select 1
      from public.documents d
      where d.id = document_id
        and (
          app_private.can_manage_study()
          or d.owner_member_id = app_private.current_member_id()
          or d.created_by = app_private.current_member_id()
        )
    )
  );

create policy "attachments delete document editors"
  on public.attachments for delete
  to authenticated
  using (
    exists (
      select 1
      from public.documents d
      where d.id = document_id
        and (
          app_private.can_manage_study()
          or d.owner_member_id = app_private.current_member_id()
          or d.created_by = app_private.current_member_id()
        )
    )
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'study-attachments',
  'study-attachments',
  false,
  20971520,
  array[
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/svg+xml'
  ]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types,
    updated_at = now();

create policy "study attachments select active"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'study-attachments' and (app_private.is_active_member() or app_private.is_bootstrap_open()));

create policy "study attachments insert active"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'study-attachments' and app_private.is_active_member());

create policy "study attachments update active"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'study-attachments' and app_private.is_active_member())
  with check (bucket_id = 'study-attachments' and app_private.is_active_member());

create policy "study attachments delete active"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'study-attachments' and app_private.is_active_member());

revoke all on schema app_private from public, anon;
grant usage on schema app_private to authenticated;

revoke execute on function app_private.current_member_id() from public, anon, authenticated;
revoke execute on function app_private.current_member_role() from public, anon, authenticated;
revoke execute on function app_private.is_active_member() from public, anon, authenticated;
revoke execute on function app_private.can_manage_study() from public, anon, authenticated;
revoke execute on function app_private.is_bootstrap_open() from public, anon, authenticated;
grant execute on function app_private.current_member_id() to authenticated;
grant execute on function app_private.current_member_role() to authenticated;
grant execute on function app_private.is_active_member() to authenticated;
grant execute on function app_private.can_manage_study() to authenticated;
grant execute on function app_private.is_bootstrap_open() to authenticated;

revoke execute on function app_private.handle_new_auth_user() from public, anon, authenticated;
revoke execute on function app_private.create_document_version() from public, anon, authenticated;
revoke execute on function app_private.add_activity_event() from public, anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'rls_auto_enable'
      and pg_get_function_identity_arguments(p.oid) = ''
  ) then
    revoke execute on function public.rls_auto_enable() from anon, authenticated, public;
  end if;
end $$;




